// text-react/src/Debug.js
import React, { Component } from 'react';

class Debug extends Component {
  render() {
    var debugStyle = {
      fill: 'rgb(77,200,242)',
      stroke: 'none'
    };
    var i = -1;

    function next_i () {
      i = i + 1;
      return 100 + i * 20;
    }
    return (
      (this.props.showDebug ?
      <g>
        <text x="100" y={next_i()} style={debugStyle}>Page: ({this.props.frameWidth}, {this.props.frameHeight})</text>
        <text x="100" y={next_i()} style={debugStyle}>Cursor: ({this.props.cursorPosX}, {this.props.cursorPosY})</text>
        <text x="100" y={next_i()} style={debugStyle}>Key: {this.props.lastKey} </text>
        <text x="100" y={next_i()} style={debugStyle}>Frame #: {this.props.frameNumber} </text>
      </g>
      : null)
    );
  }
}

export default Debug;

// vue/my-project/src/components/DebugComponent.vue
<template>
<g>
    <text x="400" y="400" class="XUI__debug_text">Cursor: {{cursor_pos_x}} {{cursor_pos_y}}</text>
    <text x="400" y="420" class="XUI__debug_text">Key: {{last_key}} </text>
    <text x="400" y="440" class="XUI__debug_text">Frame #: {{frame_number}} </text>
</g>
</template>
<script>
export default {
  name: 'DebugComponent',
  props: ['cursor_pos_x', 'cursor_pos_y', 'last_key', 'frame_number']
}
</script>
<style lang="less">
@copynot: rgb(77,200,242);

.XUI__debug_text {
    fill: @copynot;
    stroke: none;
}
</style>
