// react-template/src/Debug.js
import React, { Component } from 'react';

class Debug extends Component {
  render() {
    var debugStyle = {
      fill: 'rgb(77,200,242)',
      stroke: 'none'
    };
    return (
      <g>
        <text x="400" y="400" style={debugStyle}>Cursor: ({this.props.cursorPosX}, {this.props.cursorPosY})</text>
        <text x="400" y="420" style={debugStyle}>Key: {this.props.lastKey} </text>
        <text x="400" y="440" style={debugStyle}>Frame #: {this.props.frameNumber} </text>
      </g>
    );
  }
}

export default Debug;

// vue/my-project/src/components/Debug.vue
<template>
<g>
    <text x="400" y="400" class="XUI__debug_text">Cursor: {{cursor_pos_x}} {{cursor_pos_y}}</text>
</g>
</template>
<script>
export default {
  name: 'Debug',
  props: ['cursor_pos_x', 'cursor_pos_y']
}
</script>
<style lang="less">
@copynot: rgb(77,200,242);

.XUI__debug_text {
    fill: @copynot;
    stroke: none;
}
</style>
